# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      # 386: i386
      amd64: x86_64
# checksum:
  # name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-vault"
changelog:
  skip: true
  # sort: asc
  # filters:
  #   exclude:
  #     - '^docs:'
  #     - '^test:'
release:
  github:
    owner: internetarchive
    name: rclone
  prerelease: true
  disable: false
  header: |
    ## rclone with vault support (experimental)

    This is an release of rclone with support for the Vault
    Digital Preservation System, developed by the [Internet
    Archive](https://archive.org).

    * Date: {{ .Date }}
    * Version: {{ .Version }}
    * Branch: {{ .Branch }}
    * Tag: {{ .Tag }}
    * Commit: {{ .FullCommit }}
