# Make sure to check the documentation at https://goreleaser.com
#
# To tag the current vault branch for upload, we use the following convention:
#
# $ git tag $(git tag -l | grep -E '^v[0-9\.]+$' | tail -1)-vault-$(date +"%Y%m%d%H%M%S")-$(git rev-parse --short HEAD)
#
# Example tag would be: v1.59.1-vault-20230131181542-1da70fdd1
#
# Where v1.59.1 is the latest tag of the master branch that this branch is rebased on.
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  -
    format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
snapshot:
  name_template: "{{ incpatch .Version }}-vault"
changelog:
  skip: true
release:
  github:
    owner: internetarchive
    name: rclone
  disable: false
  header: |
    ## Rclone with Vault support (experimental)

    This is a release of Rclone with support for the [Vault
    Digital Preservation System](https://webservices.archive.org/pages/vault), developed at the [Internet
    Archive](https://archive.org).

    Setup instructions for this tool can be found in the [README.md](https://github.com/internetarchive/rclone/blob/ia-wt-1168/backend/vault/README.md).

    Note macOS users: We recommend to download the binary on the command line
    with [curl](https://curl.se/) or [wget](https://www.gnu.org/software/wget/).

    * Date: {{ .Date }}
    * Version: {{ .Version }}
    * Branch: {{ .Branch }}
    * Tag: {{ .Tag }}
    * Commit: {{ .FullCommit }}
